"""empty message

Revision ID: d618b3acc464
Revises: 9b9c41c874a0
Create Date: 2020-11-12 00:21:21.201036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd618b3acc464'
down_revision = '9b9c41c874a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekdays', sa.Column('week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekdays', 'week')
    # ### end Alembic commands ###
